### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by BaconGod** [ClusterM/retroarch-clover#1]
The nes games that run through retroarch seem to be less sharp and fuzzy.

**Comment by 1lokolo1** [comment]
This is the bilinear fillter that is on. I will research a bit to tel you how to "solved" but I thunk in reddit has info about.

Rgs.

**Comment by BaconGod** [comment]
@1lokolo1 Wow, thanks man.

**Comment by ClusterM** [comment]
Fixed.

**Comment by BaconGod** [comment]
oh wow, thanks @ClusterM, that was fast.  :)    i just need to reinstall the retroarch mod right?  do i need to uninstall the old one?

**Comment by ClusterM** [comment]
Uninstall it and install new from here: https://github.com/pcm720/retroarch-clover/releases

**Comment by BaconGod** [comment]
thanks a bunch.
