### ISSUE TITLE
Issue Playing NES games on SNESC

### ISSUE THREAD

**Issue by electrocret** [ClusterM/retroarch-clover#103]
I am using retroarch-clover 1.0 with Hakchi2 2.21c, and have tried disabling all Mods except retroarch, putting the Roms on Non-compressed. Everytime when I launch the games, the screen goes black for a few seconds then it goes back to the menu.

I am using No-Intro Roms, and here is an example command:
/bin/nes /usr/share/games/CLV-H-ZMPYZ/Adventures_of_Lolo_(USA).nes.7z

I have successfully been able to play SNES, GBA, and Genesis games in RetroArch. Am I doing something wrong, or are there NES retro-arch issues on the SNES?

**Comment by jabrevno** [comment]
Same issue here. European SNES mini, flashed custom kernel, installed Retroarch with cores, synced NES, SNES and GBA games, leaving more than half of the space empty - GBA and SNES games work, every NES game goes to black screen for a few seconds and back to the menu.
Uninstalled and reinstalled mods, deleted and re-synced games, flashed original kernel, re-flashed custom - same result.
Skimmed the GBX thread, people seem to have it work perfectly.
Hakchi ver. 2.0.21.40, according to About tab. Package is self-updating web installer, so it should be up to date. 

Any help? :/

**Comment by electrocret** [comment]
That is so weird. I tried roms from a different set, and it worked fine. None of the other system's had issues with the No-Intro roms. From what I've read No-Intro is considered the definitive Rom set to use.
