### ISSUE TITLE
RetroArch XMB menu not displaying correctly

### ISSUE THREAD

**Issue by abijanfar** [ClusterM/retroarch-clover#11]
I prefer the RetroArch XMB menu over the current default, but when I enable XMB it shows black boxes where the menu icons should be. The menus look to be functional but ugly without the icons.

**Comment by pcm720** [comment]
That's how it should be.
There are no assets for the XMB menu, they're too big to include in the main release (~20 MB).

I wanted to add the asset module just for this, but haven't had the chance to do so.

**Comment by abijanfar** [comment]
I see, looks like it is defaulting to monochrome them. If the module only includes the png for this theme it would be around 1.4 MB. Maybe it can be cut down even more, if all the images are not needed.

**Comment by pcm720** [comment]
I've added module with XMB assets.
You'll need to change assets directory location to /etc/libretro/assets or reinstall retroarch.hmod to get it working, I've updated retroarch.cfg with correct location.
