### ISSUE TITLE
[Request] BSX-Satellaview Emulation Core

### ISSUE THREAD

**Issue by atrac17** [ClusterM/retroarch-clover#111]
I don't know if it's possible, but could you look into a Emulation solution for BSX?

https://bsxproj.superfamicom.org/downloads.htm

**Comment by KMFDManic** [comment]
Done, grab SNES9X from my set.

https://github.com/KMFDManic/NESC-SNESC-Modifications/releases

**Comment by atrac17** [comment]
Done many moons ago... Now, be godlike.
