### ISSUE TITLE
Use_Nestopia.hmod Doesn't Work

### ISSUE THREAD

**Issue by raccoonmario3** [ClusterM/retroarch-clover#12]
I installed "use_nestopia.hmod" and I get sent back to the menu when I use the global command argument "--retroarch." If I don't use that command, all games just use the default emulator. Whatever I try, I can't use Nestopia with Hakchi2. Any games that should run under it simply crash and send me back to the menu. If I don't use "use_nestopia.hmod," then Retroarch uses FCEUmm, which can't run FDS games. Also, FDS games fail to run even without the Nestopia hmod, since the Retroarch hmod uses Nestopia for FDS games, which FCEUmm doesn't support.

**Comment by pcm720** [comment]
Take a look at #13

**Comment by raccoonmario3** [comment]
That solved the problem. Thanks.
