### ISSUE TITLE
Can someone help me find the file that contains the command line entry "--retroarch" after it's entered in hakchi and flashed to snes?

### ISSUE THREAD

**Issue by ihadmail** [ClusterM/retroarch-clover#125]
Im using hakchi 2.21 and Retroarch 1.0.

A game I installed, Adventures of Yogi Bear, loaded to the title screen so I thought it was good to go. A few seconds past that it freezes up.

I have already sent this console to my friend. There's no easy way for me to fix this using hakchi. He is comfortable using FTP and manually editing a text file.

I installed this game on my SNES and replicated the issue. I then added the command line argument "--retroarch" via hakchi. This fixed the issue and allowed the game to fully load.

Can someone direct me to the location of the file where this command line argument is saved so that I can compare the data between just adding the game and adding the game with the extra "--retroarch" argument?

**Comment by LeanderAT** [comment]
I don't know what you mean...location of the file where this command line is saved? 

Just load Hakchi and find the game...it has the command line for each game. Just add two versions of the ROM, one with normal SNES command line (leave it as is) and one with "-retroarch" at the end of the line.

**Comment by ihadmail** [comment]
When I add "--retroarch" in the command line, this is saved in one of the files for the rom. Possibly a configuration file in librarto folder? 

I need the location of this file. 

I fully understand how to do this in hakchi, but that's not the issue or my question. 

Thanks for the response.

**Comment by LeanderAT** [comment]
I don't know. I am a beginner, just managed to get some games running on my Snes Mini. :)

**Comment by ihadmail** [comment]
With some help from user MainHaze on reddit I have solved this.

Once the SNES has been modded and games added to it, you can use ANY computer to force retroarch to load a problem game. 

hakchi has to be open to FTP into the mini using filezilla

Navigate using FTP client (filezilla for me) to /usr/share/games
Look through all of the folders here until you find the one that contains the problem game.
Edit the .desktop file, adding "--retroarch" after "600" at the end. 
Save this edited file back to the SNES, overwriting the one that's currently there. 
Power off and close FTP client then close hakchi.
Test the SNES out and realize this solved the problem.

**Comment by ihadmail** [comment]
Ok. This solved the "--retroarch" code in the .desktop file 

I make more issues along the way though. When I load my edited .desktop file onto the SNES and power it on, I get a black screen instead of anything loading onto it.

Reset does nothing. Down select on the controller does nothing. Power off gives me the "shutting down" animation.

**Comment by LeanderAT** [comment]
Good to hear you got help! :)

Do you know where the config files for games are saved? I added a game, changed settings of it (Retro Arch)...then I only got a black screen...I removed the game, then added it again BUT it still does not work because the config file stored somewhere is still loaded although I had deleted the whole game from the SNES mini. Any ideas?

**Comment by ihadmail** [comment]
The same user on reddit came through again.

The only issue was I was using the standard Notepad to edit this file just as I did the retroarch_core_options.cfg file. He requested I download Notepad++ and give it a shot with it just as a test.

I edited the .desktop file in the /var/lib/hakchi/rootfs/usr/share/games location using Notepad++ and transferred it back into this location. I verified by transferring and opening the file in the /usr/share/games folder that the change was showing in both locations.

Powered the SNES back on with it hooked to my TV and it powered on. The game loaded properly also. 

Now if you've shipped a system to someone else and they find a game MUST be forced open with retroarch, you can walk them through updating the .desktop for that game to make it playable and they don't have to have the computer (or at least the complete file set) used to create the custom kernel.
