### ISSUE TITLE
use_nestopia doesn't work

### ISSUE THREAD

**Issue by scrcube** [ClusterM/retroarch-clover#13]
I installed it and it keeps using FCEUmm.

**Comment by 1lokolo1** [comment]
I think some change on last extension check affected the way that the templates make by pcm. Because with last retroarch.hmod changes no extra core works for me. But if uninstall retroarch.hmod module, and install my previous retroarch.hmod and all cores extra works, maybe the use_nestopia.hmod use similar way and don't work.

Rgs.

**Comment by pcm720** [comment]
Try the latest release.

**Comment by scrcube** [comment]
I just tried, but no go, I am testing with Asterix as that game only shows good graphics with nestopia, but it always shows glitchy graphics whenever I select it, meaning it defaults to using FCEUmm.

I tried several combinations, first just installing use_nestopia (NO retroarch), then both use_nestopia and retroarch. Then tried to uninstall everything and try from scratch but it doesn't work, it always defaults to using FCEUmm.

I also tried with Disney's Aladdin and Disney's Beauty and the Beast since they both also display glitches when using the default, but it doesn't work, they don't use nestopia...

**Comment by pcm720** [comment]
First, [uninstall hakchi completely](https://gbatemp.net/threads/hakchi2-nes-mini-very-simple-pimp-tool.456256/page-279#post-7118772)
Then install retroarch.hmod, and only after that install use_nestopia.hmod.

If this doesn't work (which means you're doing something wrong), force nestopia by adding "--retroarch --core nestopia" (without quotes) to command line arguments of the games

**Comment by scrcube** [comment]
I tried the instructions you mentioned with https://github.com/ClusterM/retroarch-clover/releases/ release 0.4 and with https://github.com/pcm720/retroarch-clover/releases/tag/0.4-extra release 0.4-extra and both did not work.

Appending "--retroarch --core nestopia" to the Comand Line Arguments works. So for now I'll use that since anyway the default emulator runs most of the games, just will need to add that line to the trouble games.

**Comment by pcm720** [comment]
Yes. And that's how it should be.
I guess we can consider this issue closed?

**Comment by scrcube** [comment]
The original issue is still there since supposedly when installing use_nestopia ALL games will be using that one, or is my understanding incorrect?

**Comment by pcm720** [comment]
Yes, incorrect.
After installing use_nestopia.hmod, Nestopia will be used instead of FCEUmm for unsupported games and the games with the --retroarch flag.

**Comment by scrcube** [comment]
Ok, I guess the unsupported games is not in the notes, check below it says as the ONLY NES Emulator, from this what I understand is that it will ALWAYS use nestopia for any game:

"=== Use Nestopia instead of FCEUmm ===

This module will patch /bin/nes file to use Nestopia as the only NES emulator (except kachikachi)"

**Comment by pcm720** [comment]
kachikachi is the name of NES Mini's native emulator

**Comment by scrcube** [comment]
I see, thank you for the clarification and your time, you can close this issue.
