### ISSUE TITLE
Black screen on rom start

### ISSUE THREAD

**Issue by dovanDragonCat** [ClusterM/retroarch-clover#130]
I'm using Hakchi 2.21d en Retroarch 1.0 (and -- retroarch added to the command line of the rom) on my Snes Mini but for some reason some games naming Tales of Phantasia.sfc for example, has no problem being installed but when the game is started all i get is a black screen with the selected frame around it but no sound or game to be seen.
Is there a specific way to to make it work? a way the Retroarch needs to be used? or certain .hmod that need to be used?

All other games work normally and even GBA games work perfectly.

**Comment by hbeb9786** [comment]
can you tell me what you did to resolve the issue?

**Comment by dovanDragonCat** [comment]
I made the mistake of not uninstalling the mods on my Snes mini before upgrading to a newer Hakchi and Retroarch 
So make sure you uninstall the mods with the same version you installed them with or else things will conflict with each other.
In my case i still had mods from the Hakchi 2.20 Beta version and that made a mess of things.
But now after returning to the stock settings and installing everything as normal it all worked out.
How the info helps for you :)
