### ISSUE TITLE
All non NES roms will crash

### ISSUE THREAD

**Issue by puregamingnut** [ClusterM/retroarch-clover#15]
Wonder if anyone can help all genesis and SNES games I have installed will load fine but will crash after a few seconds of play i get a black screen my nes mini will lock up pressing the power off/on does nothing i have to pull the power cable to be able to restart the nes mini i don't get any error codes the only mod I have install is standard retroarch and cloverapp. I have 33 nes game along with the pre installed 30 and 10 SNES games in a folder and 10 genesis games in a folder. All the games will lock up at random times like at start screen or at the end of a level no specific times. I have reflashed the original kernel and flashed customer kernel again with retroarch and clover.

**Comment by 1lokolo1** [comment]
Uninstall hakchi2. From kernel->uninstall
Then delete all content from \user_mods less music.hack folder. 
Download from pcm github releases 0.4-extra(in files format from releases.zip and in folder type in source.zip) the ones you prefer. In files is best. 
Open hakchi2 and sycro your games (right big button). 
Then from releases.zip extract to your \user_mods folder retroarch.hmod and inside \core_mod and core_extra_mod the .Hmod files of the module-cores of RA you want (snes9x2005 maybe ;))
Install then from hakchi2 the RA and other cores you need. 
Then power on your mini. And enjoy. 

Rgs.

**Comment by puregamingnut** [comment]
Thanks 1lokolo1 will give that a try later

**Comment by puregamingnut** [comment]
Thanks 1lokolo1 all roms are working great i have even added a few more
