### ISSUE TITLE
how to make a added rom open with retroarch?

### ISSUE THREAD

**Issue by hbeb9786** [ClusterM/retroarch-clover#151]
Hi I have found two roms not working but they also do not ask to be played with a 3rd party emulater.

I see command line argument over on the right above the box art, is there a way to use this to make the game run with the 3rd parry emulator emulator?

**Comment by gBaH0JI9I** [comment]
Add retroarch with cores to hakchi2.
Install cores to SNES.
In commsnd line:
 /bin/nes /usr/share/games/.....    - for nes games
 /bin/md /usr/share/games/......    - for Sega Genesis games (enable "genesis_plus_gx" first)
 /bin/snes /usr/share/games/...     - for SNES games to open in retroarch (snes9x2010 core).

**Comment by hbeb9786** [comment]
Ok I have Retroarch installed, what I meant was how do i was a rom, that i add, that does not ask to use a 3rd party emulator to in fact use it. Over on the RIGHT ABOVE box art there are command lines. I read some where to add --retroarch to the line but do not know how. 

here are two command lines from games that are installed
1) Working, ask for 3rd party when i added the rom
/bin/snes /usr/share/games/CLV-U-FNKWC/Terranigma_(Europe).sfrom.7z

Not working, DID NOT ask to use 3rd party rom
/bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-WIIYX/Sim_City.sfrom.7z --volume 100 -rollback-snapshot-period 600

how do i make it launch with retoarch (sim city) thanks

**Comment by hbeb9786** [comment]
Ok thank you i understood what you meant once i was staring at it, before you sync change the location hacki will add the game, so sim city once i added it was

/bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-WIIYX/Sim_City.sfrom.7z --volume 100 -rollback-snapshot-period 600 - Not Working, i changed it to:
/bin/snes /usr/share/games/CLV-U-WIIYX/Sim_City.sfrom.7z
changing the location after usr, and removing all garbarge after.7z

Thankyou

**Comment by gBaH0JI9I** [comment]
@hbeb9786 
👍 👍  👍 
in your situation, the first method:
/bin/snes /usr/share/games/CLV-U-WIIYX/Sim_City.sfrom.7z

second method:
/bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-WIIYX/Sim_City.sfrom.7z --volume 100 -rollback-snapshot-period 600 --retroarch

As you can see, in the second method at the end of the command line, simply added **--retroarch**
This key gives the command to the built-in emulator to run the game through a third party emulator.

**Comment by hbeb9786** [comment]
I will remove the game, and try the second method and let ya know. thanks Mate.
