### ISSUE TITLE
~/.config paths

### ISSUE THREAD

**Issue by abijanfar** [ClusterM/retroarch-clover#16]
Why do we have ~/.config/retroarch/something vs, ~/something paths? Makes it hard to find things on the file system when searching in the RetroArch menu. Can this be changes? Looks like some were already changed.

**Comment by pcm720** [comment]
And would you need that?
Only necessary locations were changed from ~/.config/retroarch/* to ~/*

**Comment by abijanfar** [comment]
Agreed. I will edit the file one my end if needed.
