### ISSUE TITLE
modules for BIOS for extra cores don't work

### ISSUE THREAD

**Issue by 1lokolo1** [ClusterM/retroarch-clover#17]
I update to this las 0.4-extra2 and I used a BIOS_templated to put PSX, lynx and PCE-CD bios (the correct names.extension that works in 2.11 hakchi + RA) all together in same BIOStemplate.hmod.
Also I tried only PSX bios in a BIOS_template2.hmod but same issue. I tried to put also the PSX BIOS in \user_mods\retroarch.hmod\etc\libretro\system but same issue. Always making the correct unistall modules until change when have files adding/removed. But same issue. Don't start. The other extra cores that don't need bios works ok. I think is about BIOS change folder.

Rgs.

**Comment by pcm720** [comment]
What are the names of your BIOS files? Post their MD5 hashes, too

**Comment by 1lokolo1** [comment]
Sorry the problem isn't the BIOS, are me... :(
