### ISSUE TITLE
retroarch freezing while leave it 

### ISSUE THREAD

**Issue by forsgear** [ClusterM/retroarch-clover#175]
The last version of retroarch core has resolved my problem )

**Comment by forsgear** [comment]
forgot one thing   retroarch freezing for all consoles

**Comment by forsgear** [comment]
forgot one thing   retroarch freezing for all consoles

**Comment by forsgear** [comment]
Even factory default did not fix it

**Comment by Shoothimnow** [comment]
Please close this "issue".  Your status on this issue says **Open**, which means that the problem has not been resolved
