### ISSUE TITLE
Stella not working/rom extension?

### ISSUE THREAD

**Issue by Elex163** [ClusterM/retroarch-clover#18]
Hey guys. First off great work and thanks for everything. I'm not sure if this is an issue or not but I can't get Stella Atari 2600 to work. My Roms are in .bin format. I changed them to .a26 and also .rom but none of them work. They work fine on PC. I changed the extension because I had my genesis games in .bin and they didn't work so I changed to .smd and then it work. So I figured it wouldn't read any roms with .bin. Any help would be great. Thanks.

**Comment by pcm720** [comment]
Have you installed stella core module?

**Comment by Elex163** [comment]
Yes I have. I installed the snes core and games play fine. Can't get Atari games working. Keeps booting back to menu. In the clover app it shows that Stella core is installed.

**Comment by pcm720** [comment]
What are your command line args for 2600 games in Hakchi2?

**Comment by Elex163** [comment]
I'm sorry i don't know what that means or how to check. If you tell me where to check for that I can let you know when I get back home from work later.

**Comment by pcm720** [comment]
If you don't know what that means, just download the newest release Hakchi2 (v. 2.13), remove your 2600 games, make sure they have .a26 extension and add them again

**Comment by Elex163** [comment]
Will do thanks for your help.

**Comment by Elex163** [comment]
I can confirm Stella is now working with new update 2.13. Thank you again for your help.

**Comment by pcm720** [comment]
It was working from the beginning. The only difference is that Hakchi2 2.13 automatically sets /bin/a26 because of .a26 extension.
