### ISSUE TITLE
Multiple SNES cores?

### ISSUE THREAD

**Issue by gingerbeardman** [ClusterM/retroarch-clover#19]
Each of the four SNES cores offer different compatibility, playing certain "difficult" games better than others.

It would be great to get access to all the cores and be able to choose or have certain games automatically mapped to different cores according to compatibility.

**Comment by pcm720** [comment]
Which SNES cores are you talking about?

So you're suggesting to implement a compatibility list that will switch cores automatically?
I think it's easier to let the user pick a core than to parse through all of 21344 ROMs available in GoodSNES romset.

**Comment by ajmi982** [comment]
Technically you can already do this. Before you flash the kernel in your command line arguments. Have each core assigned to a different argument. 

/Bin/(core name)

**Comment by gingerbeardman** [comment]
snes9x2002 (pocketSNES)
snes9x2005 (CATSFC)
snes9x2005_plus (CATSFC Plus)
snes9x2010 (Snes9x Next)

**Comment by pcm720** [comment]
I could not find the snes9x2005_plus for armhf architecture, but I see that snes9x2002 can be taken from Lakka. If you have a working *.so for snes9x2005_plus, point me to it, and I might add them to extra_cores in my repo.

**Comment by gingerbeardman** [comment]
could this work?
https://buildbot.libretro.com/nightly/linux/armhf/latest/

**Comment by pcm720** [comment]
I don't see snes9x2005_plus there.
snes9x2005 and snes9x2010 are already in the repository

**Comment by gingerbeardman** [comment]
Maybe they've got rid of snes9x2005_plus?

**Comment by pcm720** [comment]
Who knows.
If it's not there, I can't add it.

**Comment by pcm720** [comment]
I've added snes9x2002 to the repository with extra cores

**Comment by gingerbeardman** [comment]
Thanks!
