### ISSUE TITLE
Wrong Mapping with PDP Fight Pad (GC Controller)

### ISSUE THREAD

**Issue by mrTruch** [ClusterM/retroarch-clover#2]
When you want to play SNES is confusing.

For example in Super Mario World Run with Y and Jump with B, in a Wii classic controller or a pro controller how is just similar to a Super Nintendo controller there is no problem.

With a PDP Fight controller how is like a GAME CUBE controller Y button is above A button and is hard to run and jump.

OK, the solution is get anoher controller or remapping.

I think how there is a lot of games with same problem maybe could be a extension or shortcut to get this.

 
![two action button](https://cloud.githubusercontent.com/assets/25885652/23105921/9dc9aadc-f6e6-11e6-9750-b79d7cd63a7b.jpg)

PDP FIGHT --->GAME IDEAL REMAP ON SNES

B------>Y
A------>B
X------>A
Y------>X

Edit:

On N64 same "problem"

Y works like B
B works like A

Attached how is mapped on VC (mario Kart 64 example)
![how to n64](https://cloud.githubusercontent.com/assets/25885652/23106869/4688531e-f6f4-11e6-91a7-197e84be566f.jpg)

**Comment by pcm720** [comment]
Most likely related to #9

**Comment by pcm720** [comment]
So, about solution to this problem. I guess you can modify clovercon driver to change the buttons around, but I think that it will be a lot easier to remap the buttons in RetroArch settings.

**Comment by teconmoon** [comment]
Even if it won't be fixed, still finding this odd behavior. Remapping the buttons in RetroArch also affects all other cores (basically sacrificing every other core to fix N64 button input) and also changes the buttons used to navigate the menu.

**Comment by teconmoon** [comment]
Figured this out, to remap for the core instead of all of retroarch, to to Quick Menu -> Controls, then you can set each button to what it needs to be without affecting the other cores or the menu navigation.

Then you need to select "Save Core Remap File" afterwards, you can save controller configurations for specific games by selecting "Save Game Remap File"
