### ISSUE TITLE
PCSX Rearmed core?

### ISSUE THREAD

**Issue by gingerbeardman** [ClusterM/retroarch-clover#20]
PCSX Rearmed is good enough for certain games.

for example on my New 3DS:
the original Ridge Racer gets 45fps
card games (Jarinko Chie Hanafuda gets 50fps)
puzzle games
etc.

switching off sound gets +5fps on most games

of course some demanding games run badly, but it's worth having for those that run OK

It would be great to get it on NES MINI.

**Comment by pcm720** [comment]
PCSX ReARMed is already avaiable here:
https://github.com/pcm720/retroarch-clover/releases

You won't find extra cores in this repository.

**Comment by gingerbeardman** [comment]
Great, thanks!

**Comment by kaz321123** [comment]
Actually pcm720, you just put in the extra cores into the release, which helped me a ton!

I just played some pac-man collection on 7800 to prove it (prosystem), hehe.

By the way, thanks a ton for all your work, I really appreciate it!

**Comment by black-pudding** [comment]
How do you run PS1 titles on NESC if every single one of them weights >300Mb?

**Comment by pcm720** [comment]
Ask people on Reddit or GBATemp about this.
IIRC, they used ripped games (without CD Audio and FMV) that fit into 30 MB.
