### ISSUE TITLE
32x with PICODRIVE

### ISSUE THREAD

**Issue by tjm694** [ClusterM/retroarch-clover#21]
Just noticed the issue of why my 32x games weren't playing.  In the command line when you add a 32x Genesis game, it says "/bin/path to your software" then all the I have to manually change all the 32x games from /bin/path to your software to /bin/32x ... someone look into this and re-release the picodrive core?

Just a bug report. ;)

**Comment by pcm720** [comment]
It's not a bug, the problem is that you're using an old version of Hakchi2.
Update to Hakchi2 v 2.13
