### ISSUE TITLE
Tell me why this doesn't work ....

### ISSUE THREAD

**Issue by tjm694** [ClusterM/retroarch-clover#22]
This is the command line hakchi2 enters whenever I have it put Donkey Kong Arcade in as a full archive.  When I click on it, it blinks and then goes back to the menu selection of hakchi2.

These arcade roms are the only thing I CANNOT for the life of me to get working.

I have ALL cores installed that were included.  Any ideas?

/bin/zip /usr/share/games/nes/kachikachi/CLV-Z-YAGGN/dkong.zip

**Comment by pcm720** [comment]
/bin/zip doesn't exist.
Change "zip" to a script for a core you need.
Look at [README](https://github.com/pcm720/retroarch-clover/blob/master/README.md) for command line executables available for other cores
