### ISSUE TITLE
I cant hear sound on retroarch

### ISSUE THREAD

**Issue by NotNer0** [ClusterM/retroarch-clover#24]
I have try turn it off mute put it does not work

**Comment by pcm720** [comment]
Not enough details

**Comment by NotNer0** [comment]
Some games i can hear the audio and i cant see the games and some games just crash and some games i can play but there no audio, I turn of mute and enable the audio but nothing, reflash, reinstall mods nothing

**Comment by pcm720** [comment]
Does this happen with original 30 games?
Uninstall hakchi completely (Kernel —> Uninstall) and reinstall everything again.

**Comment by NotNer0** [comment]
No it does not, Im trying that now

**Comment by pcm720** [comment]
Don't forget to use latest Hakchi2 from
https://github.com/ClusterM/hakchi2/releases/latest
 and latest modules from
https://github.com/pcm720/retroarch-clover/releases/latest

**Comment by NotNer0** [comment]
I have been useing those, Ill tell you what happens after its done flashing

**Comment by puregamingnut** [comment]
follow what 1lokolo1 commented on mine works like a charm BTW thanks 1lokolo

Uninstall hakchi2 from your nes mini first kernel->uninstall
Then delete all content from user_mods folder apart from music.hack folder.
Download 0.4-fix 
Open hakchi2 and sync your games
Then from 0.4-fix zip download extract retroarch.hmod file and other .hmod in cores folder and put them in user_mods folder in hackchi2
Install then hmods via hakchi2 in the modules
Then power on your mini And enjoy.

Fixed my all my issues and i was having a hard time with all my roms crashing

**Comment by pcm720** [comment]
These are a little bit outdated, use 0.4-extra6 instead

**Comment by NotNer0** [comment]
Redownloading retroarch

**Comment by NotNer0** [comment]
Thank you guys reddit was not much of a help it fix

**Comment by pcm720** [comment]
So, did it help?

**Comment by puregamingnut** [comment]
Thanks pcm720 got your 0.4-extra6 now i understand what goes where you guys are awesome and very help full and do some awesome work for us. is it worth getting a wii classic control i guess retroarch supports this?

**Comment by pcm720** [comment]
Well, if you want to use all available cores, then probably yes.
Honestly, I'd rather play all these games on PC with RetroArch (or even original hardware)
