### ISSUE TITLE
Atari 2600 Games don't work 

### ISSUE THREAD

**Issue by Jan-Magerl** [ClusterM/retroarch-clover#25]
Atari 2600 Games don't work

**Comment by baconcow** [comment]
Any further details would be useful. What core did you use, etc.?

**Comment by pcm720** [comment]
They do work.
Check your command line arguments for 2600 games and make sure that they start with "/bin/a26…"

**Comment by Jan-Magerl** [comment]
Oh yeah your right, the command line was wrong,
All my 2600 Games were added with /bin/bin ...
Now it works.
Thx

**Comment by TenLosAngeles** [comment]
HUGE! Thank you!
