### ISSUE TITLE
Diagonal on wii controller does not work 

### ISSUE THREAD

**Issue by NotNer0** [ClusterM/retroarch-clover#27]

**Comment by pcm720** [comment]
Not enough details, most likely that the issue is somewhere else

**Comment by NotNer0** [comment]
I don't know, a lot of people (2) have the same problem as me, when I go diagonal I walk slow, I can tell by Mario 64.

**Comment by pcm720** [comment]
That's not RetroArch's problem

**Comment by NotNer0** [comment]
And then do what

**Comment by pcm720** [comment]
I can't help you there.
Search libretro Wiki or RetroPie Wiki for the answer or ask people on GBATemp.
