### ISSUE TITLE
(N64) Analog Sensitivity Issue

### ISSUE THREAD

**Issue by teconmoon** [ClusterM/retroarch-clover#29]
When playing a game like Super Mario 64, all the main axis work as intended (Up, Down, Left, Right) and Mario runs as usual, but if the joystick is at a diagonal (UpLeft, UpRight, DownLeft, DownRight) Mario slows to a trot as if I'm only partially pushing the joystick.

Bumped the sensitivity setting found in Quick Menu -> Options up to the maximum of 110 and dropped the deadzone to 0, which slightly alleviated the issue but didn't fully fix the issue. I feel like a higher maximum would solve this issue (sort of) but still kinda odd that the main axis and the diagonals have different sensitivities. Tried three different controllers to rule out a controller specific issue.

Not sure if this is even fixable but figured I'd report it.

Based on the design of the game you're playing it isn't as noticeable (ie Mario Kart 64 doesn't rely on diagonals hardly at all).

Edit: Saw that someone else posted this problem with basically no information and it got marked as invalid/closed, I thought this github project was for porting the various cores and optimizing them for the NES Classic Edition? I would think the fact that all classic controllers joysticks regardless of make or model responding the same on the NES Classic Edition would be something that would need to be optimized (Tried two Wii Classic Controllers and 4 Hori Battle Pads all with the same results)

**Comment by pcm720** [comment]
The problem is clearly in clovercon driver since analog sticks were never meant to be used.
I've looked into clovercon source code and found this:
```
#define DEAD_ZONE      20
#define DIAG_MAX       40
#define STICK_MAX      72
#define STICK_FUZZ     4
```
I think that you'll need to open an issue in Hakchi2 and ask Cluster to adjust these defines.

**Comment by ajmi982** [comment]
An wr fix this through in game retroarch settings??

**Comment by baconcow** [comment]
This issues sounds a lot like [the issue that was made, and closed, earlier](https://github.com/ClusterM/retroarch-clover/issues/27).

**Comment by pcm720** [comment]
Yes, but I'll keep this one open because it does have proper information unlike previous one

**Comment by baconcow** [comment]
Of course.

**Comment by ajmi982** [comment]
Can we fix this manually and just reflash an hmod instead of entire kernel? Makes playing LOZ OOT not as fun. Crawl diagonally.  Lol

**Comment by ClusterM** [comment]
Seems like clovercon driver problem. I will check it.

**Comment by ajmi982** [comment]
Wonderful. Thanks ClusterM

**Comment by NotNer0** [comment]
Didn't know what do really say, this is exactly the problem I had, now I understand what you mean by more details

**Comment by bfluryx1234** [comment]
Watching

**Comment by teconmoon** [comment]
Thanks for checking on this ClusterM and pcm720!

**Comment by ClusterM** [comment]
Fixed. You can download new clovercon mod now: https://github.com/ClusterM/hakchi2/tree/master/mods/hmods
and replace mods/hmods/clovercon.hmod if you don't want to wait for next version :)

**Comment by ajmi982** [comment]
Fantastic!!

**Comment by teconmoon** [comment]
Thanks, to get this installed just overwrite the old clovercon.hmod file and reflash the custom kernel?

**Comment by ClusterM** [comment]
teconmoon, you don't need to reflash kernel for it.
Anyway, new version will be released soon.
