### ISSUE TITLE
Vs. Unisystem: map “Insert coin“ to a button on the default gamepad.

### ISSUE THREAD

**Issue by real-amano** [ClusterM/retroarch-clover#30]
The “coin in“ function in .unif games should be mapped to a button on the default NES controller by default (if possible). I don't know what would be a sensible choice? “Down“  on the D-pad? SELECT? 

Ideally on both Retroarch cores: Nestopia and FCEUmm.

**Comment by pcm720** [comment]
I'll look into this. I think SELECT would be a better option
