### ISSUE TITLE
Has Anybody got The Simpson Arcade Working on the NES Mini?

### ISSUE THREAD

**Issue by simpsonsarcade** [ClusterM/retroarch-clover#32]
Has Anybody got The Simpson Arcade Working on the NES Mini?
Do you use MAME or another core.
The Simpsons need 3 2 ZIPs and a bios.rar.
I've seen gameplay with the mini but no instructions on how to do it

Thank You

**Comment by pcm720** [comment]
This is not a valid issue. Questions like these should be asked on Reddit or GBATemp
