### ISSUE TITLE
NES Classic Palette FBX for NES Cores

### ISSUE THREAD

**Issue by tmagri** [ClusterM/retroarch-clover#33]
The latest version of NES cores in the current build in RetroArch support [Firebrandx's NES Composite Palette Project](http://www.firebrandx.com/nespalette.html) which aims to match the colours closest to the actual NES Hardware itself. 
Can RetroArch-Clover support these pallets also since they can provide a real NES hardware experience, Thanks?

**Comment by pcm720** [comment]
I'll have to recompile FCEUmm and Nestopia to add this, but I'll look into it. This is an amazing improvement.

**Comment by pcm720** [comment]
Done.
