### ISSUE TITLE
Gba Pokémon emerald version save doesn't work

### ISSUE THREAD

**Issue by mattmame** [ClusterM/retroarch-clover#34]
On Pokémon emerald version, I can save in game. When reopen game, there's no save, only start new game

**Comment by mattmame** [comment]
Problem appears after shutting down the nes mini.

**Comment by Wyvern94** [comment]
You should use  the savestates from the nes Mini. They Do work for me but only With the mgba core

**Comment by mattmame** [comment]
Ok, I'm donna try.
I will post a new message after testing your solution.
Thx

**Comment by pcm720** [comment]
mattmame, try the latest retroarch.hmod.
Looks like SRAM was removed from /var/cache too early for mGBA to load it

**Comment by mattmame** [comment]
Hi pcm720,
I'm gonna try this evening.
I leave a post and mark the issue as solved if it works.
Thx a lot

**Comment by mattmame** [comment]
Issue fixed.
Good job, very fast fixed.
Thx a lot
