### ISSUE TITLE
Image glitch on Tokimeki Memorial @ Snes9x2005

### ISSUE THREAD

**Issue by MelonGx** [ClusterM/retroarch-clover#37]
The image:
![image](https://cloud.githubusercontent.com/assets/7697767/23640023/d49d82ae-0325-11e7-90ba-bae11bde66b1.jpeg)

Besides this, Super Mario World's Player 2 can't be controlled.

I'll try Snes9x2010 for both problems.

**Comment by pcm720** [comment]
The problem is with core itself, there's nothing we can do.

**Comment by jtgillia** [comment]
Yes, I have found there to be a bunch of sound glitches running Mario All Stars through this core.  I may switch back to SNES2010 and take my chances with the large saves.

**Comment by MelonGx** [comment]
BTW, this image glitch seems to happen on other Mouse-supported SNES games, not only Tokimeki Memorial.

**Comment by MelonGx** [comment]
Super Mario World's Player 2 problem is resolved.
It uses Player 1's controller, but not Player 2's.

**Comment by MelonGx** [comment]
Snes9x2010 fixes this image glitch.
