### ISSUE TITLE
Help with arcade games

### ISSUE THREAD

**Issue by jtgillia** [ClusterM/retroarch-clover#39]
Thanks everyone for all the work in making the NES-C extra wonderful!  This is not an issue as much as a question.  I've tried 3 different cores (mame2003, mame2000, and fba) to get 4 different arcade games to run- Pac and Pal, Pole Position, Rolling Thunder, and Moon Patrol.  Is there a certain core that can run any of these or is there a list online that shows which cores (on NES Classic) work for whixh arcade games?  These were the only games left I was having trouble with.

**Comment by pcm720** [comment]
Look at RetroPie wiki for MAME compatibility.
https://github.com/RetroPie/RetroPie-Setup/wiki/MAME

**Comment by jtgillia** [comment]
Thanks.  Looks like I'll have to wait for other cores to get those games....

**Comment by kaz321123** [comment]
I know Pac n Pal works for sure.  Make sure you have romset 0.78 and use mame2003.

Or you can get a couple of them here (pac n pal, pole position, and moon patrol at least).

https://github.com/kaz321123/Mame-Support-Files/tree/master/Mame2003%20Roms

**Comment by jtgillia** [comment]
I'm gonna download those three tonight.  Thank you, you have made my day!
