### ISSUE TITLE
MAME?

### ISSUE THREAD

**Issue by tjm694** [ClusterM/retroarch-clover#4]
Any chances of adding MAME support?  Or how to do it myself?  Thanks!!

**Comment by sanjay900** [comment]
Just drop the core in to the cores folder, and add a mame file to bin

**Comment by tjm694** [comment]
I'm a bit lost here .... I only have the retroarch.hmod in my "user_mods" directory.  There is no core directory.  Where would I put the mame core?

**Comment by sanjay900** [comment]
Oh right, you should extract that file.

**Comment by sanjay900** [comment]
note that its just a .tar file

**Comment by 1lokolo1** [comment]
It's easy I think but I only tried FBA neogeo and works ok in RA, also in mini GUI. It's amazing. Maybe I'll make a version of my RA module to share with the additions I have.

Rgs.

**Comment by tjm694** [comment]
I don't see why no one is adding the MAME core in the updates?   Any clues?

**Comment by MattMan76** [comment]
Easily doable.  I'm sure someone will take up the project.  I already have a MAME cabinet and want to keep the NESMINI for consoles otherwise I would think about doing it.

**Comment by pcm720** [comment]
Please make a module using the template and test it.
I really don't want to add cores that were not tested, and I don't have time or enough interest to test it myself.

**Comment by 1lokolo1** [comment]
I'm making test about a pal from Spain that has compile some mame2000 mame2003 mame2010 with unnecessary games(that mini NES Classic cannot handle) to reduce the core size. When are tested and ok I will make as modules and if can do it make a fork to can apport to pcm720 github request or if fail like today send to him can test and add to complete more systems. 

Rgs.

**Comment by pcm720** [comment]
MAME 2000 and MAME 2003 were added in the recent update

**Comment by 1lokolo1** [comment]
Hi pcm,

I have a mame2003 "mimimized" without clones and Quiz games(you know shitty games or useless versions clones) to a 3,5MB core size. Build by D_Skywalk the same who build caprice32, fuse and mame2000 cores. I'm making some test but appears to run some of the best 300 games for mame2003 core, very well and with less core size. When I test more. I give to you to check it.

Rgs.
