### ISSUE TITLE
MAME2003 and famicom mini.

### ISSUE THREAD

**Issue by brunobelo** [ClusterM/retroarch-clover#42]
I can't use the A button on MAME2003 when I'm on my famicom mini. The same button works on MAME2000. I think A is mapped to button 2 on MAME. Famicom mini is a little different from nes mini, as the controllers are non changeable.

I can't open an issue on PCM720 fork, so I'm here...

**Comment by pcm720** [comment]
Try to use controls remapping option in RetroArch:
https://github.com/RetroPie/RetroPie-Setup/wiki/RetroArch-Configuration#core-input-remapping
Instead of Select+X use Select+Start to open RGUI.

**Comment by brunobelo** [comment]
Yeah, the thing is, I've disabled the retroarch menu because I don't have an use for it... Or didn't at the time... If I uninstall retroarch module and reinstall, the configurations will be changed to default?

**Comment by pcm720** [comment]
Yes

**Comment by brunobelo** [comment]
Yeah, the thing is, I've disabled the retroarch menu because I don't have an use for it... Or didn't at the time... If I uninstall retroarch module and reinstall, the configurations will be changed to default?
