### ISSUE TITLE
Question : how to use Firebrandx's palettes?

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/retroarch-clover#43]
How can we use Firebrandx's more accurate palettes with Nestopia and FCEUmm for NESC?

**Comment by pcm720** [comment]
Look at the core options in RGUI

**Comment by black-pudding** [comment]
I'll do it. Thx!

**Comment by black-pudding** [comment]
I haven't seen anything straightforward linked to Firebrandx's more accurate palettes in the core option (after having loaded FCEUmm) :(

**Comment by pcm720** [comment]
Really? There's "Color Palette" setting in FCEUmm/Nestopia options.

**Comment by black-pudding** [comment]
Do I have to be running a game to see it? 
(I'm on retroarch 1.4.1)

**Comment by pcm720** [comment]
Yes

**Comment by black-pudding** [comment]
It worked, thx. The colour improvement is just massive.

(For the n00bs: I had to add the global comand-line argument "--retroarch" in the hakchi2/setting menu.)
