### ISSUE TITLE
MAME2003 : where to put neogeo.zip?

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/retroarch-clover#44]
I tried the bios template but it doesn't work for SNK games in mame2003 (zipped and unzipped). Do I have to put the bios neogeo.zip in each game folder? Or as for FBA in the first SNK game I launch?

**Comment by pcm720** [comment]
Use mame2003.hmod from GitHub repo, not from release.zip

**Comment by black-pudding** [comment]
Thx! So if I understand well, I can now put neogeo.zip anywhere I want. Right?

**Comment by pcm720** [comment]
Use BIOS template or put it in any NeoGeo game you want

**Comment by black-pudding** [comment]
Cool :)
