### ISSUE TITLE
MAME & DOSBOX zipped ROM issue

### ISSUE THREAD

**Issue by MelonGx** [ClusterM/retroarch-clover#45]
Original title: Mame2000 / Mame2003 cannot run some Mame & CPS1 games
(Firstly I thought it might be a core issue but now it seems don't)

Such as Cadillacs and Dinosaurs World 930201 (even the compatibility list said it worked), Hard head 2 (it is said that mame2010 would work) , etc.
It turned black-screen about 10-15 sec and flashed-back to main menu.

**Comment by black-pudding** [comment]
Cadillacs and Dinosaurs is said to have issues on mame2003 and Hard head 2 has a "not working" status.
https://docs.google.com/spreadsheets/d/1LP1MELCvcxu7TfiowF_0ZuvRVEMqlfQyTVetnOJvuJc/edit#gid=1744967714

**Comment by MelonGx** [comment]
@black-pudding No, it's not the reason you said. The gamelist said C&D "have issues" BUT NOT "not working".
@ClusterM @pcm720
http://gbatemp.net/threads/hakchi2-nes-mini-very-simple-pimp-tool.456256/page-389#post-7180135

For example, C&D (dino.zip) should include 16 .rom files.
But browsing dino.zip with RetroArch, it says "No items."
Then where are those 16 .rom files?
Are they properly copied into the NES mini?
Why can't it be properly copied into the NES mini?
It makes the game unable to play!

**Comment by pcm720** [comment]
RetroArch hides unsupported file formats. That's why you see "No items"
when browsing an archive.

Make sure that you use supported romset (with required BIOS images in
system folder) and that you're opening the whole archive as a game.
Don't forget that you must change /bin/zip to /bin/mame2003 in command line
arguments in Hakchi2

16 марта 2017 г. 12:17 пользователь "MelonGx" <notifications@github.com>
написал:

**Comment by MelonGx** [comment]
Then how about DOSBOX issue?
To play FD2.EXE, it requires everything non-EXE.
But in this case, DOSBOX thought everything non-EXE are missed.

**Comment by black-pudding** [comment]
Final fight works on my NES mini and I didn't put any CPS1 BIOS in the system. Are you sure your games come from a 0.78 MAME reference set?

**Comment by MelonGx** [comment]
@black-pudding Wt!? A ROM set patched for MAME2003? It's new for me.

**Comment by black-pudding** [comment]
Check here for the 0.78 MAME reference set:
 https://github.com/kaz321123/Mame-Support-Files

**Comment by MelonGx** [comment]
@black-pudding Just checked the dino.zip from it. Complete the same. Every file's CRC32 are the same.
So I don't know why it doesn't work but the compatible list said it worked.

**Comment by black-pudding** [comment]
This is what I have in my dino.zip in the 0.78 MAME reference set : 
![dino](https://cloud.githubusercontent.com/assets/26217893/23993951/fc488988-0a42-11e7-9f08-896ffcdd6d20.jpg)

**Comment by MelonGx** [comment]
![1](https://cloud.githubusercontent.com/assets/7697767/23995054/ce6f20c2-0a82-11e7-95b5-94c0c788a958.png)
@black-pudding This is mine. Does the CRC32 match yours?

**Comment by MelonGx** [comment]
@black-pudding I put the dino.zip into another Famicom Mini which only has 15MB used but no clue.
Just found that Street Fighter II' Champion Edition worked. Its ROM archive is also "No files".
So dino.zip should be really "not working".
I have to wait for mame2010 and mame2014 on NES mini.

Then what's the DOSBOX's matter?

**Comment by pcm720** [comment]
@MelonGx , everything is fine with the archive itself and the transfer process. Like I said, RetroArch lists only compatible files, so you shouldn't be able to see anything other than EXE in the first place.
The problem is probably with 7z unpacking process.
If you know how to use clovershell, run "ls /var/cache" after you launch DOSBox and post the output here.

**Comment by black-pudding** [comment]
@MelonGx here is my CRC32 list but I can't have the result in hexadecimal in my app. If you can get yours in decimal you should be able to compare :
![crc32](https://cloud.githubusercontent.com/assets/26217893/24007845/1b53612c-0a70-11e7-966f-86e7b45feb04.jpg)

**Comment by MelonGx** [comment]
@black-pudding The CRC32s are completely the same. I give up playing it until mame2010 core appears.
@pcm720 The same thing also happens on .zip archive. NES mini doesn't have a keyboard so if I can't edit the DOSBOX core I'm not able to view the file list by ls -al or dir/w.

**Comment by pcm720** [comment]
@MelonGx , that's not true.
Take a look at this:
https://github.com/ClusterM/clovershell-client
This won't enable keyboard controls in RetroArch, but it will allow you to access NESC's shell.

**Comment by MelonGx** [comment]
@pcm720 The archive is probably unable to be all-extracted to /var/cache.
I put another DOSBOX game with main program & DOS4GW.
But after running the main program, it says DOS4GW is missing.
I browse the /var/cache, only the main program is there.

**Comment by pcm720** [comment]
Are you using RGUI to browse /var/cache or clovershell-client?

**Comment by MelonGx** [comment]
@pcm720 
![default](https://cloud.githubusercontent.com/assets/7697767/24014267/3ce16128-0abf-11e7-91e9-5639df449720.png)
Back to execute FD2.EXE.
Here is the result.

**Comment by pcm720** [comment]
Okay, now that's something to work with. 
I've tried running archived DOOM with RetroArch's Windows port, and it does the same thing.
Basically, it unpacks the first exe it can find in the archive and runs it.
There are two ways I see this fixed:
1. Running unpacked files directly by placing them to the game folder (the old way)
2. Modifying the DOSBox launch script so it would manually unpack game archives into temporary folder and then passing the EXE (decide which one to pass by looking at the archive name, perhaps?) to retroarch-clover script.

**Comment by MelonGx** [comment]
I just manually uploaded all 43 files into /var/cache/ and execute FD2.EXE.
The game can be played now.
But a new problem happens - I need to configurate the key for this game, otherwise no buttons work.

**Comment by pcm720** [comment]
Use RGUI to bind gamepad keys to keyboard keys

**Comment by MelonGx** [comment]
Don't know what is RGUI.
Is there any manual method to create the controller setting?

**Comment by pcm720** [comment]
It's the menu you see when you press Select+Start.
https://github.com/RetroPie/RetroPie-Setup/wiki/RetroArch-Configuration#core-input-remapping
Instead of Select+X use Select+Start

**Comment by MelonGx** [comment]
@pcm720
RGUI - Quick Menu - Options & Controls are both not working.
I have to try PC-editing retroarch.cfg.

**Comment by MelonGx** [comment]
@pcm720 Nevermind. A friend taught me how to correctly configure the keys.
