### ISSUE TITLE
Enhancement : add the libretto core P-UAE (Amiga)

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/retroarch-clover#47]
It would be so nice!

**Comment by pcm720** [comment]
I don't see the point in adding this.
Libretro implementation of P-UAE is currently incomplete and is a pain to set up.

If you want to play around with it, use core template to make your own module.

**Comment by black-pudding** [comment]
It's indeed rational. I didn't know about the incomplete implementation :'(
