### ISSUE TITLE
[Question] MAME2003 how to save input config?

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/retroarch-clover#48]
Is it possible to save the MAME2003 input config without changing the whole retroarch input config? On a PC the config is saved automatically (using Retroarch/MAME2003) but not on the NES mini (that's why I ask this question here).

**Comment by pcm720** [comment]
Yes, look up "core remap file" and this:
https://github.com/RetroPie/RetroPie-Setup/wiki/RetroArch-Configuration#core-input-remapping

Please, for help, ask people on GBATemp or on /r/nesclassicmods subreddit
This is not a support forum.
