### ISSUE TITLE
Unable to re-flash custom kernal

### ISSUE THREAD

**Issue by retroplayer02** [ClusterM/retroarch-clover#49]
I think i messed up somewhere, was trying to install the neogeo.zip bios and i put it in the mods/hmods folder and received an error stating "Access to the path 'neogeo.zip' is denied." I restored back to original kernel and when i tried to install the custom kernel i get the same error "Access to the path 'neogeo.zip' is denied."  and I cant put any games back on it. I deleted all references to neogeo.zip in all the folders but I still cant flash custom kernel. Any help would be greatly appreciated. This error only seems to come up in 2.14b it was working fine until i tried to upload the neogeo.zip bios and accidentally put it in the wrong place. Removing all traces of the file still causes this error.

![error](https://cloud.githubusercontent.com/assets/26610896/24222405/ef80a7e4-0f1f-11e7-9a5c-c9f601e1f313.jpg)

**Comment by kaz321123** [comment]
Delete the contents inside the 'config' folder, and try again.
