### ISSUE TITLE
Game Boy/Game Boy Color Games are cropped a bit at the top and bottom

### ISSUE THREAD

**Issue by scrcube** [ClusterM/retroarch-clover#50]
You see the energy, number of metroids, etc. cropped in half in Metroid II.

The same goes for Super Mario Land, the upper part where the number of lives is is cropped in half.

So in summary for Game Boy and Game Boy Color games the screen is cropped at the top and bottom.

**Comment by pcm720** [comment]
Turn off overscan in your TV settings, this has little to do with NES Mini.
