### ISSUE TITLE
FB Alpha core doesn't work

### ISSUE THREAD

**Issue by DecMaster** [ClusterM/retroarch-clover#52]
I tried everything to load Neo Geo games but with the new version 2.14b I can't load them !
The BIOS file is in the game directory, I tried "\bin\retroarch-clover <fb_alpha>" and "\bin\fba" in the command argument and many NeoGeo roms but nothing work...

Is there a problem with the neogeo core or did I miss something ?

The hakchi tool is very well made in general anyway.

**Comment by pcm720** [comment]
Did it work before 2.14?

**Comment by DecMaster** [comment]
I didn't understand the old method to put new core on retroarch before 2.14 because I tried to launch FB_alpha like I launch a new gba or nes core for example but the games has never worked...

**Comment by pcm720** [comment]
Well, you're doing something wrong.
Update retroarch and fbalpha modules to the latest version.
You should put neogeo.zip next to one of the ROMs in the games folder of hakchi2 and change every command arg to "/bin/fba". Note that it's not "\bin\fba", backslashes in the file path do not work in *nix systems.

**Comment by DecMaster** [comment]
Thanks for your answer. It's a misspelling for the backslahses sorry.
Every modules and retroarch are the lastest releases from this github, it's why I find this strange...
If the rom file work on Kawaks (NeoGeo emulator for PC) for exemple, is there a possibility that they even don't work with the retroarch one ?

**Comment by pcm720** [comment]
Final Burn Alpha has a PC version and is available in RetroArch as a core (including PC). Better try running your ROMs on these two first.

**Comment by DecMaster** [comment]
It's a good idea. But unfortunatly they don't work too... even CPS2 games. Somes are runable with the MAME cores.
I tried also with multiple versions of roms but Retroarch seems to not like them ^^'
Is there a reference for NeoGeo Roms available on retroarch ?
(I saw with the retroarch menu on mini-nes that the cores was successfully installed)

**Comment by pcm720** [comment]
Well, if your ROMs don't work on PC, they won't work on NES Classic.

These compatibility lists should be the same for NES Classic:
https://github.com/RetroPie/RetroPie-Setup/wiki/FinalBurn-Alpha

**Comment by DecMaster** [comment]
Thanks for sharing and your help, I will get a look ;) Hope that netx time I will finally boot a NeoGep game on the Nes Mini !

**Comment by black-pudding** [comment]
@pcm720 Could you tell me what are the advantages of Fba in comparaison of mame2003 as far as the NES mini is concerned?

**Comment by pcm720** [comment]
No idea.
https://retropie.org.uk/forum/topic/2630/romsets-between-mame-and-final-burn-alpha/4
Looks like MAME's focus is accuracy while FBA is focused on speed and compatibility.
MAME2003 is based on a very old MAME release (from 2003) compared to Final Burn Alpha core (based on FBA Oct 2016 release) though, so who knows.

**Comment by lil-diabo** [comment]
Have you got the correct core for Neo-Geo?
Sounds like you're using the regular FBA core instead of the fb_alpha_neo core

**Comment by DecMaster** [comment]
I didn't see a specific Neo Geo core for the Mini-NEs for the moment instead the normal FBA core and the CPS2 one, but there are video on the net that show Neo Geo games on the Mini-NES
