### ISSUE TITLE
fceumm 1.41 doesn't auto switch to Side B of FDS games.

### ISSUE THREAD

**Issue by MattMan76** [ClusterM/retroarch-clover#54]
First of all I just want to say that I love the latest release of hakchi2! Your work is amazing!

I noticed that after this last update the Family Computer Disk System games no longer switch to the second side automatically.   Does the fceumm 1.41 core not support that option? I did get it to work by mapping some buttons in Retroarch, but that is pretty annoying.  What do you recommend?
Thanks,
Matt

**Comment by pcm720** [comment]
Neither FCEUmm nor Nestopia supports automatic disk switching.

**Comment by MattMan76** [comment]
Do you know which emulator it was that was auto disk switching for me originally? Or did I imagine that?

**Comment by pcm720** [comment]
Yes, only clover-kachikachi (built-in emulator) supports this function. It should be used as default FDS emulator.
Just make sure that there is no "--retroarch" flag in command line arguments.

**Comment by MattMan76** [comment]
I'm running the newest hakchi2 2.14b and retroarch 0.6 and these are the only switches I have for the FDS games and it still defaults to the fceumm emulator.  
--guest-overscan-dimensions 0,0,9,3
--initial-fadein-durations 10,2
--volume 75
--enable-armet
--fds-auto-disk-side-switch-on-keypress

I think retroarch is the default emulator for FDS files with these versions.

**Comment by pcm720** [comment]
That's not how it's supposed to work. Are you sure you're not using some kind of global setting for RetroArch?

**Comment by MattMan76** [comment]
I just double checked everythind. No global settings.  I found that the FDS games that have the FDS file extension are loading with clover-kachikachi.  The FDS ROMS that are named with the .nes file extension for what ever reason load with FCEUmm and respond to the select-start combo.  For example: ZeldaFDS has the file extension saved as "nes" CLV-H-ZZSQC.nes and loads with FCEUmm. MetroidFDS has the file extension as CLV-Z-CFHBD.fds and loads with clover-kachikachi.  I assume if I rename the ROMS to the correct file extension they will load with clover-kachikachi like I want them to.  I'll give that a try.

**Comment by MattMan76** [comment]
Changing file extensions solved my problem.  It's interesting how that works though.  Here are the two Desktop File Entries before and after renaming the "Doki Doki Panic" game:
Exec=/bin/clover-kachikachi-wr /usr/share/games/nes/kachikachi/CLV-H-GAARC/**CLV-H-GAARC.nes** --guest-overscan-dimensions 0,0,9,3 --initial-fadein-durations 3,2 --volume 75 --enable-armet

Exec=/bin/clover-kachikachi-wr /usr/share/games/nes/kachikachi/CLV-Z-GAARC/**CLV-Z-GAARC.fds** --guest-overscan-dimensions 0,0,9,3 --initial-fadein-durations 10,2 --volume 75 --enable-armet **--fds-auto-disk-side-switch-on-keypress**

**Comment by pcm720** [comment]
That's expected behaviour. We are using file extension to detect FDS, so the launcher script detects your FDS games as NES games with unknown mapper because of .nes extension

**Comment by MattMan76** [comment]
That does make sense. Thank you for your help! 
I wonder if that should be added to the FAQ or something. Not sure how common the problem is though.
