### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by warlockv2** [ClusterM/retroarch-clover#57]
At least controller settings, everytime i update i have to reconfigure the input settings in retroarch,  its a pain because im using a 8bito controller and its mappings are very off from the retroarch.  any way to retain our settings?

**Comment by pcm720** [comment]
Well, yes. Just save them.

**Comment by warlockv2** [comment]
yes, but how do we get them so they dont get overwritten when updating?

**Comment by lil-diabo** [comment]
You'd probably have to pull your configuration from the console using clovershell
Something like
clovershell pull /etc/libretro/retroarch.cfg retroarch.cfg
then either copy this file directly to your hmod directory or after updating, push the file
clovershell push retroarch.cfg /etc/libretro/retroarch.cfg

**Comment by warlockv2** [comment]
thats a good idea actually

**Comment by toussii** [comment]
Can you please share the config that you use for the 8bitdo?
