### ISSUE TITLE
Question : Can we update retroarch-clover to 0.7 without loosing our snes savestates? 

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/retroarch-clover#58]
Are snes9x2005's savestates compatible with snes9x2010?

**Comment by pcm720** [comment]
Not really. You can use SRAM saves, though.

**Comment by black-pudding** [comment]
Which is?

**Comment by pcm720** [comment]
I don't know what you mean by "in-game saves".
SRAM saves are cartridge saves

**Comment by black-pudding** [comment]
OK thx, with SRAM saves and passwords i can delete all my save-states and switch to snes9x2010.
