### ISSUE TITLE
Some Arcade Games Not Working with FBA and CPS2 Cores

### ISSUE THREAD

**Issue by bluesquash** [ClusterM/retroarch-clover#63]
Many thanks for the arcade cores!  I've tried running various different roms of the arcade game Dungeons & Dragons: Shadow over Mystara, but it never seems to boot up.  I tried X-Men vs Street Fighter as well, but can't get it to run either.  I've got both the fb_alpha and fb_alpha_cps2 cores installed and tried both using the /bin/fba and /bin/cps2 arguments.  I've used the fba and cps2 cores to play other arcade games (Dungeons & Dragons: Tower of Doom (CPS2), Black Tiger (FBA)).  Is there something I'm missing or not doing right, or are these games not supported?

**Comment by pcm720** [comment]
Make sure that your romsets are compatible with FinalBurn Alpha
Look at the lr-fbalpha compatibility list, it should be the same for NESC:
https://github.com/retropie/retropie-setup/wiki/FinalBurn-Alpha#lr-fbalpha

**Comment by bluesquash** [comment]
Thanks for the link to the list. It shows that  X-Men vs Street Fighter as well as Dungeons & Dragons: Shadow over Mystara are compatible. I'm not sure what I'm doing wrong as I can get other games to work. Any advice?

**Comment by pcm720** [comment]
Like I said, make sure that your roms are compatible with FinalBurn Alpha.
Other than that, I've no idea.

**Comment by bluesquash** [comment]
Finally got more, but not all, of my CPS2 games to work. I needed a BIOS image (qsound.zip) in some of my CPS2 game directories. I got some of the nonworking CPS2 games to work in Mame2003 instead. I also downloaded some different Romsets which seems to have helped. There may not be an issue with the RetroArch after all. This issue is now closed. Thanks for your help.
