### ISSUE TITLE
Feature Request: RetroArch configuration builder app

### ISSUE THREAD

**Issue by abijanfar** [ClusterM/retroarch-clover#8]
It would be super helpful if the retroarch.hmod folder had a configuration builder/editor app. This way you can configure RetroArch the way you want before flashing it to the NESC. I think the app should be simple to use and only have the most common options like mapping your controller or adjusting video options.

**Comment by MattMan76** [comment]
I would bet someone is working on this. I need the same thing.

**Comment by pcm720** [comment]
https://gbatemp.net/threads/retroinvader-a-windows-gui-tool-for-retroarch.409879/
Have you seen this program?

**Comment by ajmi982** [comment]
We can use that program then reflash RetroArch.hmod folder with the settings we get from this program? I have noticed resolutions don't seem to change when trying different ones in Glupen64 or snes9x2005

**Comment by pcm720** [comment]
Honestly, I don't know. I prefer to edit retroarch.cfg manually.
