### ISSUE TITLE
Preview Images for savestates with active overlay garbled

### ISSUE THREAD

**Issue by Localhorst86** [ClusterM/retroarch-clover#81]
Hello,

retroarch on the SNES Classic allows for use of custom overlays which are commonly used for borders. There is, however, a cosmetic issue when using borders regarding the thumbnails. As you can see in these screenshots, only the top left corner of the image on screen is visible in the thumbnail, which is part of the border/overlay.

Is there any way to avoid this? I assume this is an issue with retroarch-clover and not hakchi2 itself. If I am mistaken I can gladly move this ticket/report/request over there.
![4](https://user-images.githubusercontent.com/30772376/31342346-c3539970-ad0c-11e7-8719-e9be9ea67654.png)

![5](https://user-images.githubusercontent.com/30772376/31342324-b1cac7a0-ad0c-11e7-9f03-c11a0515c64d.png)

**Comment by Localhorst86** [comment]
If you're interested I can also provide the .cfg files to incorporate the stock borders into retroarch-clover. They will not contain the border images themselves, so they will only work with the SNES Classic, not the NES Classic.

**Comment by ClusterM** [comment]
Please try latest version, I updated fbgrab.

It's easy to create .cfg. Need to create some script to load them automatically.

**Comment by Localhorst86** [comment]
Working nicely in 0.9c. Thanks :)

**Comment by Localhorst86** [comment]
well, it actually works, but if I enable overlays the get disabled entirely. I have to re-enable them everytime i start a retroarch game.
