### ISSUE TITLE
[SNES Mini] gb and gbc games not working

### ISSUE THREAD

**Issue by frumpymoons** [ClusterM/retroarch-clover#82]
Hello I can't get Game Boy and Game Boy Color game to work.
After starting them the SNES mini returns to the home screen.

Game Boy Advance games do work. Is there a log file somewhere?

**Comment by Localhorst86** [comment]
As far as I know, gb and GBC games are using a different emulator than gba. Make sure you installed the gambatte module.

**Comment by frumpymoons** [comment]
I know already checked if it is installed. The binary is there so I am guessing it should work?

**Comment by frumpymoons** [comment]
Solved!

For some reason all my roms where corrupt.
