### ISSUE TITLE
SNES Games not working with Retroarch

### ISSUE THREAD

**Issue by sarah1971** [ClusterM/retroarch-clover#83]
Hello, I've been trying to use retroarch for several games such as Street Fighter Alpha 2, Super Street Fighter 2, and Batman Joker's Revenge but I keep getting a black screen and then it just takes me back to the main menu.  Can someone please help?  Thank you.

**Comment by sarah1971** [comment]
And yes, i am running the latest version of retroarch which is version 0.9 at the moment.  I've restored to factory settings, reflashed, and still no luck.  I'd greatly appreciate any feedback anyone may have on this.  Thanks very much.

**Comment by rhester72** [comment]
Confirmed - I did a fresh install to clear out some old shader experiments and on launch, you get a black screen for 5 seconds and back to the menu.  0.8 ironically worked fine for me (sans the scanlines overlay).

**Comment by sarah1971** [comment]
I tried 0.8 and even that did not work for me :( Hopefully there’s a fix soon.  I was really looking forward to the street fighter games.

**Comment by ClusterM** [comment]
Can you show your command line to launch it?

**Comment by Legacy1** [comment]
Hi guys, i too used 0.8 with no problems, ive just updated the latest cores and i get the above problems:
This command works in 0.8 but not 0.9:

/bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-PTFXF/Street_Fighter_Alpha_2_(USA).sfrom.7z --volume 100 -rollback-snapshot-period 600 --retroarch

**Comment by theDarkFrenchy** [comment]
Well same problem here.
I was able to play Terranigma euro (patched NTSC) perfectly with 0.8.. but it's working anymore with V 0.9.
i launch the game,
black screen for about 3 to 4 seconds,
Go back to the usual SNES mini interface. 
I try to erase --retroarch from the command line, then write it back = no go.
I try to use --retroarch with the General command line settings = no go.

For your information, my settings for terranigma :
 /bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-VJMUQ/Terranigma_(US).sfrom.7z --volume 100 -rollback-snapshot-period 600 --retroarch

**Comment by riccardocossu** [comment]
I actually managed to run Sf alpha 2 with retyroarch, no special setting with the latest version; it had some slow downs, though, but nothing terrible

**Comment by Legacy1** [comment]
Same, im back to 0.8 with no problems now.

**Comment by Bumblecito** [comment]
Same here, 0.8 works flawlessly but 0.9 cannot run games with command " --retroarch" at the end of the line.

**Comment by DefKorns** [comment]
same here. going back to 0.8

**Comment by Ixxat** [comment]
Ditto, NES & Genesis have no issues on 0.9

**Comment by dem1980** [comment]
The param "--retroarch" is broken on 0.9

Il you use the generic syntax, il works, for example "/bin/snes path/to/my/rom.7z"

**Comment by ClusterM** [comment]
Fixed. Redownload and install latest release.

**Comment by Legacy1** [comment]
Thank you.

**Comment by theDarkFrenchy** [comment]
thanks cluster !
:-)

**Comment by sarah1971** [comment]
Thank you so much! Everything works great now :)

**Comment by DefKorns** [comment]
thank you @romracer and @ClusterM
