### ISSUE TITLE
snes mini taking too long to come back to home screen with retroarch

### ISSUE THREAD

**Issue by fabiophillip** [ClusterM/retroarch-clover#85]
before i installed retroarch, returning to the home screen after pressing reset button in my snes mini took like 3 seconds, but now it takes ten! is there a way for it to go faster? this only occurs with the games not in the original games folder.

**Comment by Bumblecito** [comment]
It's normal, I suppose in next versions will be fixed.

**Comment by fabiophillip** [comment]
how do i remove retroarch, then?

**Comment by dem1980** [comment]
with retroarch-clover v0.8 :
it is very slow for me when i activate the plugin "disable thumb" on each page.
This is a known issue.

with retroarch-clover v0.9 :
it is also slow to display, when this plug in is disabled and when the icon of retroarch (cloverapp) is in the current folder

**Comment by fabiophillip** [comment]
how do I disable the plugin "disable thumb" and move the retroarch icon to other folder then?

**Comment by dem1980** [comment]
Try to rename the retroarch rom/game/app in your gamelist for example aretroarch and then sync.
Try to start a game that is in the same folder, which begin with "a..." and then start a game that is not in the same folder, for example which begin with "z...".
The Time display of both folders is the same ?

Il the plugin "disable thumbs" is activated, you should not saw thumbs under the covers in menu. Do you see them ?

**Comment by fabiophillip** [comment]
the thing is, my games all appear in the same folder because I have just added a few games, so every one of my games appear in the folder "other games...". is there a way to create folders in haxchi? Oh yeah, the original games (which are in another folder) are very quick to load and go back to the home menu.

**Comment by dem1980** [comment]
In your gamelist, do you have retroarch ? If you have it, delete it.
It is useless, unless you want to customize it. This is only a shortcut to customize it.

**Comment by fabiophillip** [comment]
i deleted it and problem solved!thanks!
