### ISSUE TITLE
Illusion of Gaia and Terranigma error

### ISSUE THREAD

**Issue by jhdgghost** [ClusterM/retroarch-clover#89]
Illusion of Gaia and Terranigma (european version) gives the error "This game pak is not designed for your SUPER FAMICOM or Super NES" with hakchi 2.21 with canoe or retroarch-clover 0.9b in SNES mini. With previous hakchi 2.20 and retroach 0.8 both works fine.

**Comment by dem1980** [comment]
Are you sure ? Retroarch is not zone limited so i will not block pal game on ntsc device.

**Comment by jhdgghost** [comment]
Yes i know is very strange but that is the message. I look in the retroach options but no find any option about region. However i observed is running to 60 fps, when the game was originally is at 50 fps. In snes mini all games are running at 60 fps maybe the conversion of hakchi2.21 to adapt it was incorrect. In the previous version was working perfectly 

This is the command line for Illusion of time 

/bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-SGDOL/Illusion_of_Time_(Spain).sfrom.7z --volume 100 -rollback-snapshot-period 600 --retroarch

Remove --retroarch command line to run the rom in canoe give the same message. The rest of snes roms i try (several jrpg with english patch) work fine.

**Comment by gnadenlos** [comment]
There is another ips patch to remove the region lock available on the internet.

**Comment by ClusterM** [comment]
hakchi2 switches ROMs to NTSC, so you need patch to remove region lock. However hakchi2 already bundled with those patches. So seems like you are using not original ROM.
