### ISSUE TITLE
Mapping all SNES Buttons with 8Bitdo Controller

### ISSUE THREAD

**Issue by MattMan76** [ClusterM/retroarch-clover#9]
When using the 8bitdo controllers I'm having trouble getting all the buttons mapped in Retroarch-Clover.  Does anyone have this working correctly?  I either end up making it so nothing works or only the original A-B buttons without X-Y-L-R.

**Comment by abijanfar** [comment]
I believe this is an issue with the 8Bitdo receiver not NESC or RetroArch. Hopefully they can release a firmware fix. http://forum.8bitdo.com/thread-1907-1-1.html

**Comment by MattMan76** [comment]
Thank you for the comment.  I will test this out with a different controller and note the results.

**Comment by pcm720** [comment]
https://www.reddit.com/r/nesclassicmods/comments/5w4c0s/8bitdo_users_new_beta_firmware_supports_all_keys/
