### ISSUE TITLE
icon of retroarch (cloverapp.zip) is broken on snes

### ISSUE THREAD

**Issue by dem1980** [ClusterM/retroarch-clover#95]
When installing the Cloverapp.zip on snes mini, the icon of Retroarch shortcut is broken.

in generic .desktop we have the path 
`Icon=/usr/share/games/CLV-x-xxxxx/CLV-x-xxxxx.png`

but in the cloverapp .desktop we have
`Icon=/usr/share/games/nes/kachikachi/CLV-Z-RARCH/CLV-Z-RARCH.png`

this not have to be on snes mini ??
`Icon=/usr/share/games/CLV-Z-RARCH/CLV-Z-RARCH.png`

**Comment by ClusterM** [comment]
Oh, really...
